spring.application.name=banking-ledger
spring.datasource.url=jdbc:postgresql://localhost:5433/banking_ledger
spring.datasource.username=banking
spring.datasource.password=banking

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
